# Generated by Django 5.2.7 on 2025-11-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
