# Generated by Django 5.2.8 on 2025-11-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_email_status_notification_sms_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=24000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='type',
            field=models.CharField(choices=[('Type 1', 'Type 1'), ('Ensuite', 'Ensuite'), ('Regular', 'Regular')], default='Regular', max_length=20),
        ),
    ]
