# Generated by Django 5.2.8 on 2025-11-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_financetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Payment Received'), ('refund', 'Refund Paid'), ('renewal', 'Renewal Payment')], max_length=20),
        ),
    ]
